import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatCurrency } from '@/lib/invoiceUtils';
import { formatDate } from '@/lib/paymentUtils';

function addHeader(doc, title, subtitle) {
  doc.setFontSize(18);
  doc.text('BELIBELI DIGITAL MANAGER', 14, 18);
  doc.setFontSize(14);
  doc.text(title, 14, 28);
  if (subtitle) {
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(subtitle, 14, 35);
    doc.setTextColor(0);
  }
}

export function downloadInvoicePdf(invoice, expand = {}) {
  const doc = new jsPDF();
  const property = expand.property_id || invoice.expand?.property_id;
  const unit = expand.unit_id || invoice.expand?.unit_id;
  const tenant = expand.tenant_id || invoice.expand?.tenant_id;

  addHeader(doc, 'Rent invoice', `Invoice #${invoice.invoice_number || invoice.id}`);

  const rows = [
    ['Invoice number', String(invoice.invoice_number || '—')],
    ['Issue date', formatDate(invoice.created)],
    ['Due date', formatDate(invoice.due_date)],
    ['Status', invoice.status || '—'],
    ['Property', property?.name || '—'],
    ['Unit', unit?.name || '—'],
    ['Tenant', tenant?.name || '—'],
    ['Amount', formatCurrency(invoice.amount)],
  ];

  autoTable(doc, {
    startY: 42,
    head: [['Field', 'Value']],
    body: rows,
    styles: { fontSize: 10 },
    headStyles: { fillColor: [41, 98, 255] },
  });

  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text('Generated by BELIBELI DIGITAL MANAGER', 14, doc.internal.pageSize.height - 14);

  doc.save(`invoice-${invoice.invoice_number || invoice.id}.pdf`);
}

export function downloadLeasePdf(lease, expand = {}) {
  const doc = new jsPDF();
  const property = expand.property_id || lease.expand?.property_id;
  const unit = expand.unit_id || lease.expand?.unit_id;
  const tenant = expand.tenant_id || lease.expand?.tenant_id;

  addHeader(doc, 'Lease summary', `Lease record`);

  const rows = [
    ['Property', property?.name || '—'],
    ['Unit', unit?.name || '—'],
    ['Tenant', tenant?.name || '—'],
    ['Start date', formatDate(lease.start_date)],
    ['End date', formatDate(lease.end_date)],
    ['Rent amount', formatCurrency(lease.rent_amount)],
    ['Status', lease.status || '—'],
  ];

  autoTable(doc, {
    startY: 42,
    head: [['Field', 'Value']],
    body: rows,
    styles: { fontSize: 10 },
    headStyles: { fillColor: [41, 98, 255] },
  });

  doc.setFontSize(9);
  doc.setTextColor(80);
  const finalY = doc.lastAutoTable?.finalY ?? 120;
  doc.text('This is a system-generated summary, not a legal contract.', 14, finalY + 10);

  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text('Generated by BELIBELI DIGITAL MANAGER', 14, doc.internal.pageSize.height - 14);

  doc.save(`lease-${lease.id}.pdf`);
}
